name: CI/CD

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      output1: ${{ steps.unit_tests.outputs.test }}
      output2: ${{ steps.git_history_test.outputs.test }}
    strategy:
      matrix:
        node: [ '10.x', '12.x', '14.x' ]
    name: Node ${{ matrix.node }}
    steps:
    - uses: actions/checkout@v2
    - run: |
        git remote set-branches --add origin master
        git fetch
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}
    - name: Install Dependencies
      run: npm ci
      env:
        NODE_ENV: development
    - name: Unit Tests
      id: unit_tests
      run: ./node_modules/.bin/jest
      env:
        NODE_ENV: production
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Git History Test
      id: git_history_test
      run: npm run test:git-history
      env:
        NODE_ENV: production
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Lockfile Lint Test
      run: npm run test:lockfile
      env:
        NODE_ENV: production
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Lint
      run: npm run lint
      env:
        NODE_ENV: production
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  release:
    runs-on: ubuntu-latest
    needs: tests
    steps:
    - run: echo ${{needs.tests.outputs.output1}} ${{needs.tests.outputs.output2}}
